Welcome to the WU-FTPD version 2.8.0-CC5 unoffical patch release!

WU-FTPD is a powerful and full-featured replacement FTP server daemon. The
last known official release by the WU-FTPD Development Group was 2.6.2 on
November 29, 2001.  (Replacement because most people tended to replace 
the basic FTP daemons found on base operating systems.)

Since that time members of the Group continued to work on the code until 
eventually work stopped and languished for some years.  Those who still
had access to the newest codebase tested out new features and applied
successive security fixes.  However, sporadic outages affecting access
to the WU-FTPD site stalled further work and today it appears to be gone.

This release is based on the latest known codebase to exist, and CC 
designates a release by the tiny contingent of Sylvain Robitaille and
William F. Sotomayor.  I am grateful for Sylvain's assistance and patience
in providing advice and archiving the front page of the WU-FTPD web site.

Unlike most patch releases, this release is the complete codebase.  This
has been done to avoid distributing ever bigger patches against the 2.6.2
tarball.

You should definitely consult the CHANGES, README and INSTALL pages in this
release to see what's new and fixed (there's quite a lot).

Also, pardon the dust of this release.  There is still much work to be
done in integrating patches and features which have been left outstanding 
for the past several years.  Then there are all the details like dealing
with dead websites, defunct mailing lists and other pointers that no
longer exist or aren't valid.

If you wish to send patches for this patchset, feel free to visit 
http://www.wfms.org/wu-ftpd/, http://wu-ftpd.therockgarden.ca/ or
http://www.wu-ftpd.info/ for the latest patches or contact info.

wfms & sr
